In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Question 1: Create a 4X2 integer array and Prints its attributes

###### np.empty(shape, dtype=float, order='C')  
    Return a new array of given shape and type, without initializing entries

In [6]:
arr = np.empty([4, 2], dtype=np.uint16)
print("Printing Array: ", arr)
print()
print("Printing NumPy array Attributes\n")
print("1> Array Shape is: ", arr.shape)
print("2>. Array dimensions are", arr.ndim)
print("3>. Length of each element of array in bytes is: ", arr.itemsize)

Printing Array:  [[32696  1052]
 [    0     0]
 [    1     0]
 [ 8296 28257]]

Printing NumPy array Attributes

1> Array Shape is:  (4, 2)
2>. Array dimensions are 2
3>. Length of each element of array in bytes is:  2


### Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [13]:
arr = np.arange(100, 200, 10).reshape(5, 2)
print("Creating 5X2 array using numpy.arange")
print(arr)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


### Question 3: Following is the provided numPy array. return array of items in the third column from all rows

In [18]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print("Printing Input Array")
print(sampleArray)
print("\nPrinting array of items in the third column from all rows")
print(sampleArray[:, 1])

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Printing array of items in the third column from all rows
[22 55 88]


### Question 4: Following is the given numpy array return array of odd rows and even columns

In [25]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print("Printing input array:")
print(sampleArray)
print("\nPrinting array of odd rows and even columns")
print(sampleArray[0:sampleArray.shape[0]:2, 1:sampleArray.shape[1]:2])

Printing input array:
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


### Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square of each element

In [30]:
array1 = np.array([[5, 6, 9], [21, 18, 27]])
array2 = np.array([[15, 33, 24], [4, 7, 1]])
print("Addition of 2 array is:")

array3 = array1 + array2
print(array3)

print("\nResult array after calculating the square of all elements:")
print(np.power(array3, 2))


Addition of 2 array is:
[[20 39 33]
 [25 25 28]]

Result array after calculating the square of all elements:
[[ 400 1521 1089]
 [ 625  625  784]]


### Question 6: Split the array into four equal-sized sub-arrays

In [38]:
array1 = np.arange(10, 34, 1).reshape(8, 3)
newarray = np.array_split(array1, 4)
print("Creating 8X3 array using numpy.arange")
print(array1)
print("\nDividing 8X3 array into 4 sub array")
print(newarray)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


### Question 7; Sort following NumPy array

#### 7.1: Sort by second row

In [45]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("Original array: ")
print(sampleArray)

print("\nSorting Original array by second row")
newarray = sampleArray[:,sampleArray[1,:].argsort()]
print(newarray)

Original array: 
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]


#### 7.2: Sort by second column

In [53]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("Original array:")
print(sampleArray)

print("\nSorting Original array by secoond column")
newarray = sampleArray[sampleArray[:,1].argsort()]
print(newarray)

Original array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


### Question 8: Following is the 2-D array. Print max from axis 0 and min from axis 1

###### np.amin(a, axis=None)
    Function to get the minimum value from a Numpy array
    Argument:
        a: numpy array from which it needs to find the minimum value
        axis: It's optional, and if not provided then it will flattened the
              passed numpy array and returns min value in it
              + if axis=0: return array containing min value for each columns
              + if axis=1: return array containing min value for each rows

In [56]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("Original array: ")
print(sampleArray)

print("\nPrinting amin of axis 1:")
arrax1 = np.amin(sampleArray, axis=1)
print(arrax1)

print("\nPrinting amax of axis 0:")
arrax0 = np.amax(sampleArray, axis=0)
print(arrax0)

Original array: 
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Printing amin of axis 1:
[34 12 53]

Printing amax of axis 0:
[82 94 73]


### Question 9: Following is the input NumPy array delete column two and insert following new column in its place.

In [61]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

print("Original array: ")
print(sampleArray)

print("\nArray after deleting  column 2 on axis 1: ")
a_del = np.delete(sampleArray, 1, 1)
print(a_del)

print("\nArray after inserting column 2 on axis 1: ")
a_insert = np.insert(a_del, 1, newColumn, axis=1)
print(a_insert)

Original array: 
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Array after deleting  column 2 on axis 1: 
[[34 73]
 [82 12]
 [53 66]]

Array after inserting column 2 on axis 1: 
[[34 10 73]
 [82 10 12]
 [53 10 66]]
